# Generated by Django 5.2.11 on 2026-02-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='oidc_sub',
            field=models.CharField(blank=True, db_index=True, help_text='Auth0のUser ID（例: auth0|507f1f77bcf86cd799439011）', max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='custom_user_email_55dec9_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['oidc_sub'], name='custom_user_oidc_su_281e27_idx'),
        ),
    ]
