name: Frontend CI/CD (Production)

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-production.yml'
      - '.github/workflows/reusable-frontend-test.yml'
  pull_request:
    branches: [main]
    paths: ['frontend/**']

jobs:
  test:
    name: Test (Production)
    uses: ./.github/workflows/reusable-frontend-test.yml
    with:
      environment: production
      strict-mode: true
      coverage-threshold: 70
    secrets: inherit

  e2e:
    name: E2E Tests (Pre-deployment)
    runs-on: ubuntu-latest
    needs: test
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          working-directory: frontend
      
      - name: Get Playwright version
        id: playwright-version
        run: echo "version=$(node -p "require('./package.json').devDependencies['@playwright/test']")" >> $GITHUB_OUTPUT
        working-directory: frontend
      
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}
      
      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium firefox webkit
        working-directory: frontend
      
      - name: Install Playwright system dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps chromium firefox webkit
        working-directory: frontend
      
      - name: Run E2E tests with MSW (all browsers)
        run: npm run test:e2e
        working-directory: frontend
        env:
          E2E_TEST_EMAIL: ${{ secrets.E2E_TEST_EMAIL }}
          E2E_TEST_PASSWORD: ${{ secrets.E2E_TEST_PASSWORD }}
      
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-production
          path: frontend/playwright-report/
          retention-days: 30

  deploy-notification:
    name: Deployment Notification
    runs-on: ubuntu-latest
    needs: [test, e2e]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production
    
    steps:
      - name: Create summary
        run: |
          echo "## 🚀 Frontend Deployment (Production)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Environment:** \`production\`" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** \`main\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Pre-deployment Checks" >> $GITHUB_STEP_SUMMARY
          echo "✅ Unit/Integration tests passed (70%+ coverage)" >> $GITHUB_STEP_SUMMARY
          echo "✅ E2E tests passed (all browsers, MSW mocked)" >> $GITHUB_STEP_SUMMARY
          echo "✅ Build successful" >> $GITHUB_STEP_SUMMARY
          echo "✅ Security audit passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Deployment" >> $GITHUB_STEP_SUMMARY
          echo "🔄 Cloudflare Pages is deploying" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Frontend URL:** ${{ vars.FRONTEND_URL }}" >> $GITHUB_STEP_SUMMARY
          echo "**Backend API:** ${{ vars.VITE_BASE_API_URL }}" >> $GITHUB_STEP_SUMMARY