name: Reusable Frontend Tests

on:
  workflow_call:
    inputs:
      environment:
        description: Environment name (staging/production)
        required: true
        type: string
      strict-mode:
        description: Fail on linting errors
        required: false
        type: boolean
        default: false
      coverage-threshold:
        description: Minimum test coverage percentage
        required: false
        type: number
        default: 0

env:
  NODE_VERSION: '20'

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      
      - name: Run ESLint
        run: npm run lint
        working-directory: frontend
        continue-on-error: ${{ !inputs.strict-mode }}
      
      - name: Run Prettier
        run: npx prettier --check "src/**/*.{js,jsx,ts,tsx,css,json}"
        working-directory: frontend
        continue-on-error: ${{ !inputs.strict-mode }}

  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      
      - name: Run TypeScript compiler
        run: npx tsc --noEmit
        working-directory: frontend

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      
      - name: Run tests
        run: npm run test -- --coverage --watchAll=false
        working-directory: frontend
        env:
          VITE_BASE_API_URL: ${{ vars.VITE_BASE_API_URL }}
      
      - name: Check coverage threshold
        if: inputs.coverage-threshold > 0
        run: |
          COVERAGE=$(cat frontend/coverage/coverage-summary.json | jq '.total.lines.pct')
          if (( $(echo "$COVERAGE < ${{ inputs.coverage-threshold }}" | bc -l) )); then
            echo "❌ Coverage ($COVERAGE%) is below threshold (${{ inputs.coverage-threshold }}%)"
            exit 1
          fi
          echo "✅ Coverage is sufficient: $COVERAGE%"
      
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./frontend/coverage/coverage-final.json
          flags: frontend-${{ inputs.environment }}
          name: frontend-${{ inputs.environment }}-coverage
        continue-on-error: true

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      
      - name: Build
        run: npm run build
        working-directory: frontend
        env:
          VITE_BASE_API_URL: ${{ vars.VITE_BASE_API_URL }}
          NODE_ENV: ${{ inputs.environment }}
      
      - name: Check build output
        run: |
          if [ ! -d "frontend/dist" ]; then
            echo "❌ Build failed: dist directory not found"
            exit 1
          fi
          
          echo "✅ Build successful"
          echo "Build size: $(du -sh frontend/dist | cut -f1)"
          
          if [ "${{ inputs.environment }}" == "production" ]; then
            if find frontend/dist -name "*.map" | grep -q .; then
              echo "⚠️  Warning: Source maps found in production build"
            fi
          fi
      
      - name: Upload build artifacts
        if: inputs.environment == 'production'
        uses: actions/upload-artifact@v4
        with:
          name: frontend-${{ inputs.environment }}-build-${{ github.sha }}
          path: frontend/dist
          retention-days: 30

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Run npm audit
        run: |
          if [ "${{ inputs.strict-mode }}" == "true" ]; then
            npm audit --audit-level=high
          else
            npm audit --audit-level=moderate
          fi
        working-directory: frontend
        continue-on-error: ${{ !inputs.strict-mode }}