name: Terraform Format

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-fmt.yml'
  push:
    branches: [main, develop]
    paths:
      - 'terraform/**'

jobs:
  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.14.0
      
      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive -diff
        working-directory: terraform
        continue-on-error: true
      
      - name: Comment PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request' && steps.fmt.outcome == 'failure'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### ⚠️ Terraform Format Issues
            
            Some Terraform files are not formatted correctly.
            
            **Fix with:**
            \`\`\`bash
            cd terraform
            terraform fmt -recursive
            git add .
            git commit -m "style: format terraform files"
            \`\`\`
            
            **Status:** ${{ steps.fmt.outcome }}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
      
      - name: Fail if format issues
        if: steps.fmt.outcome == 'failure'
        run: |
          echo "::error::Terraform files are not formatted. Run 'terraform fmt -recursive' to fix."
          exit 1