name: Terraform Plan

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'terraform/**'
      - 'backend/.env.example'
      - 'backend/requirements.txt'
      - 'backend/config/settings.py'
      - 'frontend/.env.example'
      - 'frontend/package.json'
      - '.github/workflows/terraform-plan.yml'

# Terraform Cloud を使用するため、並列実行を防ぐ
concurrency:
  group: terraform-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  detect-changes:
    name: Detect Changed Environments
    runs-on: ubuntu-latest
    outputs:
      terraform-staging: ${{ steps.filter.outputs.terraform-staging }}
      terraform-production: ${{ steps.filter.outputs.terraform-production }}
      terraform-modules: ${{ steps.filter.outputs.terraform-modules }}
      backend-config: ${{ steps.filter.outputs.backend-config }}
      frontend-config: ${{ steps.filter.outputs.frontend-config }}
      should-run-staging: ${{ steps.decision.outputs.staging }}
      should-run-production: ${{ steps.decision.outputs.production }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            terraform-staging:
              - 'terraform/envs/staging/**'
            terraform-production:
              - 'terraform/envs/production/**'
            terraform-modules:
              - 'terraform/modules/**'
            backend-config:
              - 'backend/.env.example'
              - 'backend/requirements.txt'
              - 'backend/config/settings.py'
            frontend-config:
              - 'frontend/.env.example'
              - 'frontend/package.json'
      
      - name: Decide which plans to run
        id: decision
        run: |
          # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          # Staging Plan の判定
          # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          
          SHOULD_RUN_STAGING=false
          
          # Staging Terraformファイルの変更
          if [ "${{ steps.filter.outputs.terraform-staging }}" == "true" ]; then
            SHOULD_RUN_STAGING=true
            echo "🔵 Staging Terraform files changed"
          fi
          
          # Modules の変更（Stagingに影響）
          if [ "${{ steps.filter.outputs.terraform-modules }}" == "true" ]; then
            SHOULD_RUN_STAGING=true
            echo "🔵 Modules changed (affects Staging)"
          fi
          
          # アプリ設定のみの変更はスキップ（無風プラン防止）
          if [ "${{ steps.filter.outputs.backend-config }}" == "true" ] || [ "${{ steps.filter.outputs.frontend-config }}" == "true" ]; then
            if [ "$SHOULD_RUN_STAGING" == "false" ]; then
              echo "⚠️  App config changed but no Terraform changes - skipping Staging plan"
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "## ℹ️ Configuration Change Detected (Staging)" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "Application configuration changed but Terraform files unchanged." >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "**Action:** Terraform plan skipped (would result in 'No changes')" >> $GITHUB_STEP_SUMMARY
            fi
          fi
          
          echo "staging=$SHOULD_RUN_STAGING" >> $GITHUB_OUTPUT
          
          # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          # Production Plan の判定
          # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          
          SHOULD_RUN_PRODUCTION=false
          
          # Production Terraformファイルの変更
          if [ "${{ steps.filter.outputs.terraform-production }}" == "true" ]; then
            SHOULD_RUN_PRODUCTION=true
            echo "🔴 Production Terraform files changed"
          fi
          
          # Modules の変更（Productionに影響）
          # 【重要】develop向けPRでもProductionへの影響を確認
          if [ "${{ steps.filter.outputs.terraform-modules }}" == "true" ]; then
            SHOULD_RUN_PRODUCTION=true
            echo "🔴 Modules changed (affects Production)"
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "## ⚠️ Shared Module Change Detected" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Module changes affect both Staging AND Production.**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Even though this is a \`${{ github.base_ref }}\` PR, we're showing Production plan to:" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Verify production impact early" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Avoid surprises during main branch deployment" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ Enable informed decision-making" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            if [ "${{ github.base_ref }}" == "develop" ]; then
              echo "**Note:** This is a preview. Actual production deployment happens after merging to \`main\`." >> $GITHUB_STEP_SUMMARY
            fi
          fi
          
          # アプリ設定のみの変更はスキップ（無風プラン防止）
          if [ "${{ steps.filter.outputs.backend-config }}" == "true" ] || [ "${{ steps.filter.outputs.frontend-config }}" == "true" ]; then
            if [ "$SHOULD_RUN_PRODUCTION" == "false" ]; then
              echo "⚠️  App config changed but no Terraform changes - skipping Production plan"
            fi
          fi
          
          echo "production=$SHOULD_RUN_PRODUCTION" >> $GITHUB_OUTPUT

  notify-config-only-change:
    name: Notify Config-Only Change
    runs-on: ubuntu-latest
    needs: detect-changes
    if: |
      (needs.detect-changes.outputs.backend-config == 'true' || 
       needs.detect-changes.outputs.frontend-config == 'true') &&
      needs.detect-changes.outputs.should-run-staging == 'false' &&
      needs.detect-changes.outputs.should-run-production == 'false'
    
    steps:
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const backendChanged = '${{ needs.detect-changes.outputs.backend-config }}' === 'true';
            const frontendChanged = '${{ needs.detect-changes.outputs.frontend-config }}' === 'true';
            
            let changedFiles = [];
            if (backendChanged) {
              changedFiles.push('- Backend config (`.env.example`, `requirements.txt`, `settings.py`)');
            }
            if (frontendChanged) {
              changedFiles.push('- Frontend config (`.env.example`, `package.json`)');
            }
            
            const output = `### ℹ️ Configuration Change Detected
            
            Application configuration changed but Terraform files unchanged.
            
            **Files changed:**
            ${changedFiles.join('\n')}
            
            **Action:** Terraform plan skipped (would result in 'No changes')
            
            **This is normal if:**
            - Adding environment variables not managed by Terraform
            - Updating dependencies that don't affect infrastructure
            - Changing app-level settings
            
            **Action required if:**
            - New environment variables need to be added to GitHub Secrets
            - Infrastructure changes are needed (e.g., new services, databases)
            
            → In that case, update Terraform files in this PR.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

  plan-staging:
    name: Plan (Staging)
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.should-run-staging == 'true'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.14.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Show detected changes
        run: |
          echo "## 🔍 Detected Changes (Staging)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.detect-changes.outputs.terraform-staging }}" == "true" ]; then
            echo "- ✅ Staging Terraform files" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.detect-changes.outputs.terraform-modules }}" == "true" ]; then
            echo "- ✅ Terraform modules" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.detect-changes.outputs.backend-config }}" == "true" ]; then
            echo "- ℹ️  Backend config (FYI only)" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.detect-changes.outputs.frontend-config }}" == "true" ]; then
            echo "- ℹ️  Frontend config (FYI only)" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: terraform
        continue-on-error: true
      
      - name: Terraform Init (Staging)
        run: terraform init
        working-directory: terraform/envs/staging
      
      - name: Terraform Validate (Staging)
        run: terraform validate
        working-directory: terraform/envs/staging
      
      - name: Terraform Plan (Staging)
        id: plan
        run: |
          terraform plan -no-color -out=tfplan
          terraform show -no-color tfplan > plan.txt
        working-directory: terraform/envs/staging
        continue-on-error: true
      
      - name: Comment PR (Staging)
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('terraform/envs/staging/plan.txt', 'utf8');
            
            const output = `### Terraform Plan (Staging)
            
            <details>
            <summary>Show Plan</summary>
            
            \`\`\`terraform
            ${plan.slice(0, 65000)}
            \`\`\`
            
            </details>
            
            **Workspace:** \`django-react-staging\`
            **Status:** ${{ steps.plan.outcome }}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

  plan-production:
    name: Plan (Production)
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.should-run-production == 'true'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.14.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Show detected changes
        run: |
          echo "## 🔍 Detected Changes (Production)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.detect-changes.outputs.terraform-production }}" == "true" ]; then
            echo "- ✅ Production Terraform files" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.detect-changes.outputs.terraform-modules }}" == "true" ]; then
            echo "- ✅ Terraform modules" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: terraform
        continue-on-error: true
      
      - name: Terraform Init (Production)
        run: terraform init
        working-directory: terraform/envs/production
      
      - name: Terraform Validate (Production)
        run: terraform validate
        working-directory: terraform/envs/production
      
      - name: Terraform Plan (Production)
        id: plan
        run: |
          terraform plan -no-color -out=tfplan
          terraform show -no-color tfplan > plan.txt
        working-directory: terraform/envs/production
        continue-on-error: true
      
      - name: Comment PR (Production)
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('terraform/envs/production/plan.txt', 'utf8');
            
            const output = `### Terraform Plan (Production)
            
            <details>
            <summary>Show Plan</summary>
            
            \`\`\`terraform
            ${plan.slice(0, 65000)}
            \`\`\`
            
            </details>
            
            **Workspace:** \`django-react-production\`
            **Status:** ${{ steps.plan.outcome }}
            
            ⚠️  **Production環境への変更です。慎重にレビューしてください。**`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });