/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン
         * @description メールアドレスとパスワードでログインします。
         *
         *             **機能:**
         *             - HttpOnly CookieにJWTトークンを設定
         *             - ログイン履歴を記録（MotherDuck Analytics）
         *
         *             **レート制限:** 5回/5分
         *
         *             **成功時の動作:**
         *             1. アクセストークン（5分間有効）をCookieに設定
         *             2. リフレッシュトークン（1日間有効）をCookieに設定
         *             3. ログインイベントをMotherDuckに記録
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description カスタムログアウトビュー
         *
         *     機能:
         *         - 分析ログ記録（MotherDuck）
         *
         *     エラーハンドリング:
         *         - 分析ログエラー: ErrorMonitor.capture_and_continueで隔離
         */
        get: operations["auth_logout_retrieve"];
        put?: never;
        /**
         * ログアウト
         * @description 現在のセッションからログアウトします。
         *
         *             **機能:**
         *             - リフレッシュトークンをブラックリストに追加
         *             - Cookieをクリア
         *             - ログアウトイベントを記録（MotherDuck Analytics）
         *
         *             **注意:** ログアウト後は、再度ログインが必要です。
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Calls Django Auth SetPasswordForm save method.
         *
         *     Accepts the following POST parameters: new_password1, new_password2
         *     Returns the success/fail message.
         */
        post: operations["auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Calls Django Auth PasswordResetForm save method.
         *
         *     Accepts the following POST parameters: email
         *     Returns the success/fail message.
         */
        post: operations["auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Password reset e-mail link is confirmed, therefore
         *     this resets the user's password.
         *
         *     Accepts the following POST parameters: token, uid,
         *         new_password1, new_password2
         *     Returns the success/fail message.
         */
        post: operations["auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/registration/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新規登録
         * @description 新規ユーザーを登録します。
         *
         *             **機能:**
         *             - HttpOnly CookieにJWTトークンを自動設定
         *             - ウェルカムメールを非同期送信（QStash経由）
         *             - 登録イベントを記録（MotherDuck Analytics）
         *
         *             **レート制限:** 3回/1時間
         *
         *             **成功時の動作:**
         *             1. ユーザー作成
         *             2. アクセストークン（5分間有効）をCookieに設定
         *             3. リフレッシュトークン（1日間有効）をCookieに設定
         *             4. ウェルカムメールを非同期で送信（失敗してもユーザー作成は成功）
         *             5. 登録イベントをMotherDuckに記録（失敗してもユーザー作成は成功）
         */
        post: operations["auth_registration_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/send-welcome-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * [内部API] ウェルカムメール送信
         * @description QStashから呼ばれる内部エンドポイント。直接呼び出し不可。
         *
         *             **セキュリティ:**
         *             - QStash署名検証（HMAC-SHA256）
         *             - IPアドレス制限なし（署名のみで認証）
         *
         *             **リトライ:**
         *             - QStashが自動リトライ（最大3回）
         *             - 5秒、10秒、15秒の間隔
         *
         *             **エラー時の動作:**
         *             - 500エラー: QStashが自動リトライ
         *             - 400エラー: リトライなし（データ不正）
         */
        post: operations["auth_send_welcome_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["auth_token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields.
         */
        get: operations["auth_user_retrieve"];
        /**
         * @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields.
         */
        put: operations["auth_user_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Reads and updates UserModel fields
         *     Accepts GET, PUT, PATCH methods.
         *
         *     Default accepted fields: username, first_name, last_name
         *     Default display fields: pk, username, email, first_name, last_name
         *     Read-only fields: pk, email
         *
         *     Returns UserModel fields.
         */
        patch: operations["auth_user_partial_update"];
        trace?: never;
    };
    "/api/v1/todos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Todoリスト取得
         * @description ログインユーザーに紐づくTodoアイテムの一覧を取得します。
         */
        get: operations["todos_list"];
        put?: never;
        /**
         * Todo作成
         * @description 新しいTodoアイテムを作成します。
         *
         *             作成後、非同期でベクトルインデックスに追加されます（QStash経由）。
         */
        post: operations["todos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Todo詳細取得
         * @description 指定されたIDのTodoアイテムの詳細を取得します。
         */
        get: operations["todos_retrieve"];
        /**
         * Todo更新（全体）
         * @description 指定されたIDのTodoアイテムを更新します。
         *
         *             更新後、非同期でベクトルインデックスが更新されます（QStash経由）。
         */
        put: operations["todos_update"];
        post?: never;
        /**
         * Todo削除
         * @description 指定されたIDのTodoアイテムを削除します。
         *
         *             削除後、非同期でベクトルインデックスからも削除されます（QStash経由）。
         */
        delete: operations["todos_destroy"];
        options?: never;
        head?: never;
        /**
         * Todo更新（部分）
         * @description 指定されたIDのTodoアイテムの一部を更新します。
         *
         *             更新後、非同期でベクトルインデックスが更新されます（QStash経由）。
         */
        patch: operations["todos_partial_update"];
        trace?: never;
    };
    "/api/v1/todos/bulk-index/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 一括ベクトルインデックス
         * @description 既存のTodoをベクトルインデックスに一括追加します。
         *
         *             非同期処理（QStash経由）でバックグラウンド実行されます。
         *             初期データ投入やリインデックス時に使用。
         */
        post: operations["todos_bulk_index_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/progress-stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 進捗分布統計
         * @description 進捗率の分布を20%刻みで取得します。Redisキャッシュを使用（15分間）。
         */
        get: operations["todos_progress_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * セマンティック検索
         * @description 自然言語でTodoを検索します。
         *
         *             Google Gemini APIによるベクトル検索を使用し、
         *             「明日の会議関連」などの曖昧な検索が可能です。
         */
        get: operations["todos_search_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 優先度別統計
         * @description 優先度ごとのTodo件数を取得します。Redisキャッシュを使用（15分間）。
         */
        get: operations["todos_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/send-welcome-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * [内部API] ウェルカムメール送信
         * @description QStashから呼ばれる内部エンドポイント。直接呼び出し不可。
         *
         *             **セキュリティ:**
         *             - QStash署名検証（HMAC-SHA256）
         *             - IPアドレス制限なし（署名のみで認証）
         *
         *             **リトライ:**
         *             - QStashが自動リトライ（最大3回）
         *             - 5秒、10秒、15秒の間隔
         *
         *             **エラー時の動作:**
         *             - 500エラー: QStashが自動リトライ
         *             - 400エラー: リトライなし（データ不正）
         */
        post: operations["webhooks_send_welcome_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description ログイン・登録APIの共通レスポンス用シリアライザー
         *
         *     ログインと登録で同じレスポンス構造を使用するため、
         *     共通のシリアライザーとして定義。
         */
        AuthResponse: {
            /** @description ユーザー情報 */
            readonly user: components["schemas"]["CustomUser"];
            /** @description アクセストークン（Cookieにも設定される） */
            readonly access: string;
            /** @description リフレッシュトークン（Cookieにも設定される） */
            readonly refresh: string;
        };
        /**
         * @description emailベース認証用のカスタム登録シリアライザ
         *
         *     - usernameフィールドを削除（emailを主キーとして使用）
         *     - first_name/last_nameフィールドを追加
         *     - サービス層経由でユーザー作成
         *
         *     エラーハンドリング:
         *         - メールアドレス重複: UserAlreadyExistsError → 統一エラーハンドラーが処理
         *         - その他のエラー: 統一エラーハンドラーが処理
         */
        CustomRegisterRequest: {
            /** Format: email */
            email: string;
            password1: string;
            password2: string;
            /** @description ユーザーの名 */
            first_name?: string;
            /** @description ユーザーの姓 */
            last_name?: string;
        };
        /**
         * @description 現在のユーザー情報を返すシリアライザ
         *
         *     読み取り専用フィールド:
         *         - id: ユーザーID
         *         - email: メールアドレス
         *         - is_staff: スタッフ権限
         */
        CustomUser: {
            readonly id: number;
            /**
             * メールアドレス
             * Format: email
             */
            readonly email: string;
            /** 名 */
            first_name?: string;
            /** 姓 */
            last_name?: string;
            /**
             * スタッフ権限
             * @description ユーザーが管理サイトにログイン可能かどうかを示します。
             */
            readonly is_staff: boolean;
        };
        /**
         * @description 現在のユーザー情報を返すシリアライザ
         *
         *     読み取り専用フィールド:
         *         - id: ユーザーID
         *         - email: メールアドレス
         *         - is_staff: スタッフ権限
         */
        CustomUserRequest: {
            /** 名 */
            first_name?: string;
            /** 姓 */
            last_name?: string;
        };
        LoginRequest: {
            username?: string;
            /** Format: email */
            email?: string;
            password: string;
        };
        PasswordChangeRequest: {
            new_password1: string;
            new_password2: string;
        };
        /** @description Serializer for confirming a password reset attempt. */
        PasswordResetConfirmRequest: {
            new_password1: string;
            new_password2: string;
            uid: string;
            token: string;
        };
        /** @description Serializer for requesting a password reset e-mail. */
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        /**
         * @description 現在のユーザー情報を返すシリアライザ
         *
         *     読み取り専用フィールド:
         *         - id: ユーザーID
         *         - email: メールアドレス
         *         - is_staff: スタッフ権限
         */
        PatchedCustomUserRequest: {
            /** 名 */
            first_name?: string;
            /** 姓 */
            last_name?: string;
        };
        /**
         * @description Todoの作成・更新用シリアライザー
         *
         *     - userはread_only（API側でログインユーザーを自動紐付け）
         *     - バリデーションエラーは統一エラーハンドラーで処理
         */
        PatchedTodoRequest: {
            todo_title?: string;
            priority?: components["schemas"]["PriorityEnum"];
            progress?: number;
        };
        /**
         * @description * `LOW` - 低
         *     * `MEDIUM` - 中
         *     * `HIGH` - 高
         * @enum {string}
         */
        PriorityEnum: "LOW" | "MEDIUM" | "HIGH";
        RestAuthDetail: {
            readonly detail: string;
        };
        /**
         * @description Todoの作成・更新用シリアライザー
         *
         *     - userはread_only（API側でログインユーザーを自動紐付け）
         *     - バリデーションエラーは統一エラーハンドラーで処理
         */
        Todo: {
            readonly id: number;
            /**
             * メールアドレス
             * Format: email
             */
            readonly user: string;
            todo_title: string;
            priority?: components["schemas"]["PriorityEnum"];
            progress?: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description Todoの作成・更新用シリアライザー
         *
         *     - userはread_only（API側でログインユーザーを自動紐付け）
         *     - バリデーションエラーは統一エラーハンドラーで処理
         */
        TodoRequest: {
            todo_title: string;
            priority?: components["schemas"]["PriorityEnum"];
            progress?: number;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        TokenVerifyRequest: {
            token: string;
        };
        /**
         * @description ウェルカムメール送信Webhookのペイロードバリデーション
         *
         *     QStashから呼ばれるWebhook用のバリデーター
         */
        WelcomeEmailWebhookRequest: {
            /** Format: email */
            email: string;
            first_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        non_field_errors?: string[];
                    };
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail?: string;
                    };
                };
            };
        };
    };
    auth_logout_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ログアウトしました。 */
                        detail?: string;
                    };
                };
            };
        };
    };
    auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChangeRequest"];
                "multipart/form-data": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestAuthDetail"];
                };
            };
        };
    };
    auth_registration_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomRegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomRegisterRequest"];
                "multipart/form-data": components["schemas"]["CustomRegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        detail?: string;
                        data?: Record<string, never>;
                    };
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail?: string;
                    };
                };
            };
        };
    };
    auth_send_welcome_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WelcomeEmailWebhookRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WelcomeEmailWebhookRequest"];
                "multipart/form-data": components["schemas"]["WelcomeEmailWebhookRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                        message_id?: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        email?: string[];
                        first_name?: string[];
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        detail?: string;
                    };
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerifyRequest"];
                "multipart/form-data": components["schemas"]["TokenVerifyRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_user_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomUser"];
                };
            };
        };
    };
    auth_user_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CustomUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomUserRequest"];
                "multipart/form-data": components["schemas"]["CustomUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomUser"];
                };
            };
        };
    };
    auth_user_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCustomUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCustomUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedCustomUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomUser"];
                };
            };
        };
    };
    todos_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        detail?: string;
                    };
                };
            };
        };
    };
    todos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TodoRequest"];
                "multipart/form-data": components["schemas"]["TodoRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        detail?: string;
                    };
                };
            };
        };
    };
    todos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this todo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        detail?: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        detail?: string;
                    };
                };
            };
        };
    };
    todos_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this todo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TodoRequest"];
                "multipart/form-data": components["schemas"]["TodoRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        detail?: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        detail?: string;
                    };
                };
            };
        };
    };
    todos_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this todo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        detail?: string;
                    };
                };
            };
        };
    };
    todos_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this todo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTodoRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTodoRequest"];
                "multipart/form-data": components["schemas"]["PatchedTodoRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        detail?: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        detail?: string;
                    };
                };
            };
        };
    };
    todos_bulk_index_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                        status?: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        detail?: string;
                    };
                };
            };
        };
    };
    todos_progress_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        range_0_20?: number;
                        range_21_40?: number;
                        range_41_60?: number;
                        range_61_80?: number;
                        range_81_100?: number;
                    };
                };
            };
        };
    };
    todos_search_retrieve: {
        parameters: {
            query: {
                /** @description 最小類似度スコア（デフォルト: 0.5、範囲: 0.0-1.0） */
                min_score?: number;
                /** @description 検索クエリ（例: "明日の会議関連"） */
                q: string;
                /** @description 取得件数（デフォルト: 5、最大: 20） */
                top_k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        query?: string;
                        results?: {
                            id?: number;
                            score?: number;
                            todo_title?: string;
                        }[];
                        count?: number;
                    };
                };
            };
        };
    };
    todos_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        priority?: string;
                        count?: number;
                    }[];
                };
            };
        };
    };
    webhooks_send_welcome_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WelcomeEmailWebhookRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WelcomeEmailWebhookRequest"];
                "multipart/form-data": components["schemas"]["WelcomeEmailWebhookRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                        message_id?: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        email?: string[];
                        first_name?: string[];
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        detail?: string;
                    };
                };
            };
        };
    };
}
